# Full Name: Navneet Kaur, ID: 8946587, Class: Database Automation
name: CI/CD for MySQL Database

on:
  push:
    branches:
      - main  # Run the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3.x version

    - name: Install MySQL connector
      run: |
        pip install mysql-connector-python

    - name: Run SQL script on Azure MySQL
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python -c "
        import mysql.connector as mysql;
        conn = mysql.connect(
            host='${{ env.DB_HOST }}',
            user='${{ env.DB_USER }}',
            password='${{ env.DB_PASSWORD }}',
            database='${{ env.DB_NAME }}'
        );
        cursor = conn.cursor();
        with open('update_projects_schema.sql', 'r') as file:
            sql_script = file.read();
        for statement in sql_script.split(';'):
            if statement.strip():
                cursor.execute(statement);
        conn.commit();
        cursor.close();
        conn.close();
        "
